apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend-app
  labels:
    app: udagram-frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-frontend-app
  template:
    metadata:
      labels:
        app: udagram-frontend-app
    spec:
      containers:
      - name: udagram-frontend
        image: ricardiles/udagram-frontend
        args: ["serve", "8100", "--address", "0.0.0.0"]
        ports:
        - containerPort: 8100